### ISSUE TITLE
Page not loading correctly

### ISSUE THREAD

**Issue by xcln** [eustasy/uptimerobot-status-page#2]
Hello,

Not sure what is causing this.

Using the default config and even editing it, the page will not parse correctly.

![Image of Error]
(http://i.imgur.com/vGhl4w8.png)

**Comment by lewisgoddard** [comment]
Hey there, it looks like there's

**Comment by pmoreland** [comment]
I'm seeing the same thing. Any ideas? I copied directly from the .zip, and tried from the raw on git.

**Comment by lewisgoddard** [comment]
@xcln @pmoreland Try now, I think I've fixed it in 2faae3df4842384f13570078a532bcbf3b2a0fb6
